[rospy.client][INFO] 2022-03-17 16:28:26,914: init_node, name[/listener], pid[20212]
[xmlrpc][INFO] 2022-03-17 16:28:26,916: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2022-03-17 16:28:26,918: ROS Slave URI: [http://ubuntu:41453/]
[xmlrpc][INFO] 2022-03-17 16:28:26,919: Started XML-RPC server [http://ubuntu:41453/]
[rospy.impl.masterslave][INFO] 2022-03-17 16:28:26,920: _ready: http://ubuntu:41453/
[xmlrpc][INFO] 2022-03-17 16:28:26,924: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-03-17 16:28:26,926: Registering with master node http://localhost:11311
[rospy.init][INFO] 2022-03-17 16:28:27,019: registered with master
[rospy.rosout][INFO] 2022-03-17 16:28:27,020: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-17 16:28:27,026: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-17 16:28:27,029: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-17 16:28:27,098: topic[/video/click] adding connection to [http://ubuntu:45985/], count 0
[rospy.internal][INFO] 2022-03-17 16:28:27,245: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-17 16:52:02,803: topic[/video/click] adding connection to [http://ubuntu:33417/], count 1
[rosout][INFO] 2022-03-17 16:52:03,609: --------------------
[rosout][INFO] 2022-03-17 16:52:06,291: --------------------
[rosout][INFO] 2022-03-17 16:52:09,454: --------------------
[rosout][INFO] 2022-03-17 16:52:14,098: --------------------
[rosout][INFO] 2022-03-17 16:52:17,562: --------------------
[rosout][INFO] 2022-03-17 16:52:20,476: --------------------
[rosout][INFO] 2022-03-17 16:52:53,778: --------------------
[rosout][INFO] 2022-03-17 16:52:54,390: --------------------
[rosout][INFO] 2022-03-17 16:52:55,875: --------------------
[rosout][INFO] 2022-03-17 16:52:56,759: --------------------
[rosout][INFO] 2022-03-17 16:52:57,715: --------------------
[rosout][INFO] 2022-03-17 16:53:18,484: --------------------
[rosout][INFO] 2022-03-17 16:53:18,796: --------------------
[rosout][INFO] 2022-03-17 16:53:22,063: --------------------
[rosout][INFO] 2022-03-17 16:53:23,395: --------------------
[rosout][INFO] 2022-03-17 16:53:27,448: --------------------
[rosout][INFO] 2022-03-17 16:53:28,240: --------------------
[rosout][INFO] 2022-03-17 16:54:51,621: --------------------
[rosout][INFO] 2022-03-17 16:54:52,125: --------------------
[rosout][INFO] 2022-03-17 16:54:57,957: --------------------
[rosout][INFO] 2022-03-17 16:54:59,999: --------------------
[rosout][INFO] 2022-03-17 16:55:09,137: --------------------
[rosout][INFO] 2022-03-17 16:55:11,913: --------------------
[rosout][INFO] 2022-03-17 16:55:14,877: --------------------
[rosout][INFO] 2022-03-17 16:55:17,719: --------------------
[rosout][INFO] 2022-03-17 17:22:54,196: --------------------
[rosout][INFO] 2022-03-17 20:29:41,526: --------------------
[rosout][INFO] 2022-03-17 20:29:43,678: --------------------
[rosout][INFO] 2022-03-17 20:31:13,559: --------------------
[rosout][INFO] 2022-03-17 20:32:30,581: --------------------
[rospy.internal][ERROR] 2022-03-17 20:32:38,563: Unable to initiate TCP/IP socket to ubuntu:36989 (http://ubuntu:33417/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2022-03-17 20:32:39,569: Unknown error initiating TCP/IP socket to ubuntu:36989 (http://ubuntu:33417/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-03-17 20:32:39,569: topic[/video/click] removing connection to http://ubuntu:33417/
[rospy.internal][INFO] 2022-03-17 20:33:48,630: topic[/video/click] adding connection to [http://ubuntu:42701/], count 1
[rosout][INFO] 2022-03-17 20:34:28,284: --------------------
[rosout][INFO] 2022-03-17 20:36:23,691: --------------------
[rospy.internal][INFO] 2022-03-17 23:01:43,870: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2022-03-17 23:01:45,613: Unable to initiate TCP/IP socket to ubuntu:39973 (http://ubuntu:42701/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2022-03-17 23:01:46,619: Unknown error initiating TCP/IP socket to ubuntu:39973 (http://ubuntu:42701/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-17 23:01:46,620: topic[/video/click] removing connection to http://ubuntu:42701/
[rospy.core][INFO] 2022-03-17 23:17:56,227: signal_shutdown [signal-2]
[rospy.registration][WARNING] 2022-03-17 23:17:56,230: cannot unregister with master due to network issues
[rospy.internal][WARNING] 2022-03-17 23:17:56,230: Unknown error initiating TCP/IP socket to ubuntu:36081 (http://ubuntu:45985/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-17 23:17:56,231: topic[/video/click] removing connection to http://ubuntu:45985/
[rospy.impl.masterslave][INFO] 2022-03-17 23:17:56,232: signal-2
[rospy.core][INFO] 2022-03-17 23:17:56,364: signal_shutdown [atexit]
