{
    "code": "FRA_LINK_BASE_GENERIC", 
    "logs": [
        "Traceback (most recent call last):", 
        "", 
        "  File \"freedomrobotics/link_base.py\", line 578, in freedomrobotics.link_base.LinkUploader.__loop_connection_check_to_freedom_api", 
        "", 
        "Exception: Could not connect to Freedom API after 3 attempts. No Internet connection.", 
        ""
    ], 
    "level": "fatal", 
    "errorMessage": "Unhandled exception in Link `agent_link` freedom api connection check loop: <type 'exceptions.Exception'> Could not connect to Freedom API after 3 attempts. No Internet connection.", 
    "component": "agent", 
    "attributes": {
        "python": {
            "implementation": "CPython", 
            "version": "2.7.17", 
            "build": [
                "default", 
                "Feb 27 2021 15:10:58"
            ]
        }, 
        "thread": {
            "daemon": false, 
            "name": "freedom_agent_link_connection_check_thread"
        }, 
        "geo": {
            "query": "Could not get ip: HTTPConnectionPool(host='ip.42.pl', port=80): Max retries exceeded with url: /raw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8de8e050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))", 
            "message": "invalid query"
        }, 
        "system": {
            "linux_dist": [
                "Ubuntu", 
                "18.04", 
                "bionic"
            ], 
            "ip": "Could not get ip: HTTPConnectionPool(host='ip.42.pl', port=80): Max retries exceeded with url: /raw (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8de8e050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))", 
            "user": "ubuntu", 
            "arch": "Unknown: aarch64", 
            "service": "systemd", 
            "hostname": "ubuntu", 
            "environment": {
                "LANG": "C.UTF-8", 
                "SHELL": "/bin/bash", 
                "ROS_DISTRO": "melodic", 
                "ROS_VERSION": "1", 
                "JOURNAL_STREAM": "9:43275", 
                "PYTHONPATH": "/opt/ros/melodic/lib/python2.7/dist-packages", 
                "ROS_ETC_DIR": "/opt/ros/melodic/etc/ros", 
                "ROS_ROOT": "/opt/ros/melodic/share/ros", 
                "ROSLISP_PACKAGE_DIRECTORIES": "/home/ubuntu/catkin_ws/devel/share/common-lisp", 
                "LOGNAME": "ubuntu", 
                "USER": "ubuntu", 
                "ROS_MASTER_URI": "http://localhost:11311", 
                "PATH": "/opt/ros/melodic/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", 
                "PKG_CONFIG_PATH": "/home/ubuntu/catkin_ws/devel/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig", 
                "HOME": "/home/ubuntu", 
                "ROS_PACKAGE_PATH": "/home/ubuntu/catkin_ws/src:/opt/ros/melodic/share", 
                "CMAKE_PREFIX_PATH": "/home/ubuntu/catkin_ws/devel:/opt/ros/melodic", 
                "LD_LIBRARY_PATH": "/home/ubuntu/catkin_ws/devel/lib:/opt/ros/melodic/lib", 
                "ROS_PYTHON_VERSION": "2", 
                "INVOCATION_ID": "f5b2befe00b343f5b475ebc305179e63"
            }, 
            "platform": "Linux-5.4.0-1047-raspi-aarch64-with-Ubuntu-18.04-bionic", 
            "version": "#52~18.04.1-Ubuntu SMP PREEMPT Wed Nov 24 12:29:36 UTC 2021", 
            "release": "5.4.0-1047-raspi", 
            "docker": false, 
            "os": "Linux", 
            "processor": "aarch64"
        }, 
        "freedom_robotics": {
            "device": "D36F4D9E51F228A3B221D203CB1", 
            "freedom_python_module_version": "0.1.165", 
            "token": "***C8972355", 
            "account": "A139C78C471C762F34F31F8DD", 
            "code_branch": "release"
        }
    }
}