[rospy.client][INFO] 2022-01-28 19:23:55,672: init_node, name[/rostopic_30547_1643397835568], pid[30547]
[xmlrpc][INFO] 2022-01-28 19:23:55,674: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-01-28 19:23:55,676: Started XML-RPC server [http://ubuntu:45979/]
[rospy.impl.masterslave][INFO] 2022-01-28 19:23:55,677: _ready: http://ubuntu:45979/
[rospy.init][INFO] 2022-01-28 19:23:55,679: ROS Slave URI: [http://ubuntu:45979/]
[xmlrpc][INFO] 2022-01-28 19:23:55,681: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-01-28 19:23:55,683: Registering with master node http://localhost:11311
[rospy.init][INFO] 2022-01-28 19:23:55,781: registered with master
[rospy.rosout][INFO] 2022-01-28 19:23:55,782: initializing /rosout core topic
[rospy.rosout][INFO] 2022-01-28 19:23:55,789: connected to core topic /rosout
[rospy.simtime][INFO] 2022-01-28 19:23:55,793: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-01-28 19:23:56,100: topic[/video/click] adding connection to [http://ubuntu:35815/], count 0
[rospy.internal][INFO] 2022-01-28 19:23:56,102: topic[/video/click] adding connection to [http://ubuntu:43159/], count 1
[rospy.internal][ERROR] 2022-01-28 19:23:56,112: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:23:56,114: unable to create subscriber transport: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped].  Will try again in 0.5s
[rospy.internal][INFO] 2022-01-28 19:23:56,151: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2022-01-28 19:23:57,125: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:23:58,129: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:24:00,133: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:24:04,140: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:24:12,153: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:24:28,175: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:25:00,209: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:25:32,244: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

[rospy.internal][ERROR] 2022-01-28 19:26:04,284: Unable to initiate TCP/IP socket to ubuntu:45069 (http://ubuntu:35815/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [nav_msgs/Odometry] vs. [geometry_msgs/PointStamped]

